### ISSUE TITLE
【CA】人材派遣協会との提携形態について

### ISSUE THREAD

**Issue by HiromiMatsumoto** [saiki-jp/bizdev#109]
## 概要
- 人材派遣協会との提携形態について
## 目的
- 人材派遣協会との提携形態を決めるため
## タスク
- [人材派遣協会との提携形態の案を出す]

## 終了条件
- [人材派遣協会との提携形態の案を出す] 

## 期限
12月8日（日）

**Comment by Yoshiki-Koizumi** [comment]
https://saik.esa.io/posts/17
