### ISSUE TITLE
【CA】営業の準備をスプシ or esaでチェックリストにまとめる

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#118]
## 概要
- 同じ上
https://saik.esa.io/posts/21
## 目的
- 
## タスク
- [ ]

## 終了条件
- [ ]

**Comment by sugipy** [comment]
https://saik.esa.io/posts/21
>質問の意図を共有してる状態で別の人が質問をするか、質問リストを作る

**Comment by Yoshiki-Koizumi** [comment]
https://saik.esa.io/posts/67
