### ISSUE TITLE
【CA】営業の反省会のフォーマットを決める

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#120]
## 概要
- 
## 目的
- 
## タスク
- [ ]

## 終了条件
- [ ]

**Comment by sugipy** [comment]
https://saik.esa.io/posts/21/
- 今後の採用計画
     - 出所者以前の採用上京
     - 温度感
     - 日本職親を採用した経緯

**Comment by Yoshiki-Koizumi** [comment]
https://saik.esa.io/posts/66
