### ISSUE TITLE
【CS】スプレットシートでCSのチェックリストを作る

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#146]
## 概要
- 
## 目的
- エイケンホームのCSを今週中にできたらやりたいので、急ぎで作る

## タスク
- [ ] 以下のシートにチェックリストを入れる
https://docs.google.com/spreadsheets/d/1kg2NzYklITKCLKL144zjtyL_sJfY6maxDetwOlhAaC4/edit?folder=158OocYktyUzaEZAo0FidcZlPbQ8sUS0a#gid=0
## 終了条件
- [ ]

**Comment by sugipy** [comment]
https://docs.google.com/spreadsheets/d/10cdDjbZeXtiW-z1zk04SV9tELPKiObJV5JYlJ64v_yk/edit#gid=0

**Comment by sugipy** [comment]
@Yoshiki-Koizumi 
ニッコー技研のものを参考に修正する

**Comment by Yoshiki-Koizumi** [comment]
1/7 done
これをフォーマットにしてコピーして使う
https://docs.google.com/spreadsheets/d/1kg2NzYklITKCLKL144zjtyL_sJfY6maxDetwOlhAaC4/edit?folder=158OocYktyUzaEZAo0FidcZlPbQ8sUS0a&pli=1#gid=647242514
