### ISSUE TITLE
企画書を作成する

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#63]
## 概要
-
## 目的
- 営業のアウトバウンドメールに添付するため
- 行政の方など、営業以外の場面で説明するときに使うため
- 読み手は保護司を想定

## タスク
- [ ] 

## 終了条件
- [ ] 

## 参考
[CASH](https://speakerdeck.com/kanakokawahara/cash-poziteibuna-ojin-falsebiao-xian?slide=9)
![image.png](https://images.zenhubusercontent.com/5bf4b5c547b5f22e11d48f68/ef0fd05c-8819-480e-8cfb-7105fd6e2678)
![image.png](https://images.zenhubusercontent.com/5bf4b5c547b5f22e11d48f68/b5ef3e61-5b3c-4d90-8422-6b11ebe23ef0)
![image.png](https://images.zenhubusercontent.com/5bf4b5c547b5f22e11d48f68/dfb8e1f4-dcb8-47f3-9d37-832aaf47aafa)
![image.png](https://images.zenhubusercontent.com/5bf4b5c547b5f22e11d48f68/74d5ea0a-0108-45d7-b377-e666ea697c6a)

[株式会社10X - Culture Deck](https://speakerdeck.com/yamotty/zhu-shi-hui-she-10x-culture-deck)

![image.png](https://images.zenhubusercontent.com/5bf4b5c547b5f22e11d48f68/32cc515b-02ce-4c0d-9f7f-7541c4d69392)

**Comment by Katsuya-Masaka** [comment]
SAIKIの概要書
