### ISSUE TITLE
【DEV】indexページをlpに自動で遷移するようにする

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#86]
## 概要
- 
## 目的
- 
## タスク
- [ ]

## 終了条件
- [ ]

**Comment by Yoshiki-Koizumi** [comment]
12/1 
tryしたが一旦stay

**Comment by sugipy** [comment]
20191220
これにした
![image](https://user-images.githubusercontent.com/36855334/71263160-b48cc100-2384-11ea-95ae-f029fed47ad7.png)
