### ISSUE TITLE
【PM】採用ページの要件定義

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#89]
## 概要
- 
## 目的
- 
## タスク
- [ ]

## 終了条件
- [ ] 

## 備考
chanceやwantedlyを参考にする
https://www.human-comedy.com/求人・企業広告掲載のご案内/

**Comment by Yoshiki-Koizumi** [comment]
12/1
進捗なし

**Comment by HiromiMatsumoto** [comment]
採用ページの要件定義て何？

**Comment by sugipy** [comment]
https://docs.google.com/spreadsheets/d/1aWoI7Jdj8jmEy4n6YrN54Fmvx78D_GtSUs7eGJRmwoI/edit#gid=580112355
![Uploading image.png…]()
