### ISSUE TITLE
【DEV】SAIKI JOURNALのデザインを良くする

### ISSUE THREAD

**Issue by sugipy** [saiki-jp/bizdev#95]
## 概要
- 
## 目的
- 
## タスク
- [ ]

## 終了条件
- [ ]

**Comment by sugipy** [comment]
ドメインをサブドメインに変更する。
wordpressもう一度構築してからデザイン変更

**Comment by Yoshiki-Koizumi** [comment]
サーバーを建て替えるためスタック

**Comment by sugipy** [comment]
- 以下のように色をSAIKIイエローにした。
- DigitalOceanでサーバーを立てたのでサブドメインの設定に成功した
![image](https://user-images.githubusercontent.com/36855334/71304512-45a67b00-240b-11ea-97f5-1fbbd9515e1c.png)
