### ISSUE TITLE
【CA】営業資料に作りたい世界・ロードマップを入れる

### ISSUE THREAD

**Issue by Yoshiki-Koizumi** [saiki-jp/bizdev#99]
## 概要
- 
## 目的
- 
## タスク
- [ ]

## 終了条件
- [ ]

**Comment by sugipy** [comment]
営業資料に追加完了した
![image](https://user-images.githubusercontent.com/36855334/71267711-a9d72980-238e-11ea-9452-97a77ff3ed68.png)
